name: CI Pipeline

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./codebase/rdicidr-0.1.0
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setting Up NodeJS version
        uses: actions/setup-node@v4
        with:
          node-version: '15'
          
      - name: Install Dependencies
        run: npm install
      
      - name: Run Lint
        run: npm run lint
      
      - name: Run Prettier
        run: npm run prettier
      
      - name: Run Tests
        run: CI=true npm run test
      
      - name: Build
        run: npm run build